=== Drag147/Lab1XMLRead/Resources/Formula1.xsd
<?xml version="1.0"?>
<xs:schema xmlns="Formula1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="Formula1"
           elementFormDefault="qualified">
    <xs:element name="Formula_1">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Pilots">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Personal_pilot_number" type="xs:string"/>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Surname" type="xs:string"/>
                            <xs:element name="Date_of_birth" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Bolids">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name_bolid" type="xs:string" />
                            <xs:element name="Name_engine" type="xs:string" />
                            <xs:element name="Name_chassis" type="xs:string" />
                            <xs:element name="Year_bolid" type="xs:gYear"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Teams">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name_team" type="xs:string"/>
                            <xs:element name="Year_team" type="xs:gYear"/>
                            <xs:element name="Name_leader_team" type="xs:string"/>
                            <xs:element name="Surname_leader_team" type="xs:string"/>
                            <xs:element name="Country_base_location" type="xs:string"/>
                            <xs:element name="Name_bolid" type="xs:string"/>
                            <xs:element name="Personal_number_first_pilot" type="xs:short"/>
                            <xs:element name="Personal_number_second_pilot" type="xs:short"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Grand_prix">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Number" type="xs:long"/>
                            <xs:element name="Year" type="xs:gYear"/>
                            <xs:element name="Host_country" type="xs:string"/>
                            <xs:element name="Name_track" type="xs:string"/>
                            <xs:element name="Number_circles" type="xs:short"/>
                            <xs:element name="Track_km" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Results_qualification">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Id_result" type="xs:long"/>
                            <xs:element name="Id_grand_prix" type="xs:long"/>
                            <xs:element name="Date_qual" type="xs:date"/>
                            <xs:element name="Posittion" type="xs:byte"/>
                            <xs:element name="Number_pilot" type="xs:short"/>
                            <xs:element name="Time" type="xs:time"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Results_race">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Id_result" type="xs:long"/>
                            <xs:element name="Id_grand_prix" type="xs:long"/>
                            <xs:element name="Date_race" type="xs:date"/>
                            <xs:element name="Posittion" type="xs:byte"/>
                            <xs:element name="Number_pilot" type="xs:short"/>
                            <xs:element name="Time" type="xs:time"/>
                            <xs:element name="Elimination" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Drag147/Lab1XMLRead/Resources/Formula 1 one line.xml
<!DOCTYPE Formula_1 [
        <!ELEMENT Formula_1 (Pilots|Bolids|Teams|Grand_prix|Results_qualification|Results_race)*>
        <!ATTLIST Formula_1
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT Pilots (Personal_pilot_number|Name|Surname|Date_of_birth)*>
        <!ELEMENT Personal_pilot_number (#PCDATA)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Surname (#PCDATA)>
        <!ELEMENT Date_of_birth (#PCDATA)>
        <!ELEMENT Bolids (Name_bolid|Name_engine|Name_chassis|Year_bolid)*>
        <!ELEMENT Name_bolid (#PCDATA)>
        <!ELEMENT Name_engine (#PCDATA)>
        <!ELEMENT Name_chassis (#PCDATA)>
        <!ELEMENT Year_bolid (#PCDATA)>
        <!ELEMENT Teams (Name_team|Year_team|Name_leader_team|Surname_leader_team|Country_base_location|Name_bolid|Personal_number_first_pilot|Personal_number_second_pilot)*>
        <!ELEMENT Name_team (#PCDATA)>
        <!ELEMENT Year_team (#PCDATA)>
        <!ELEMENT Name_leader_team (#PCDATA)>
        <!ELEMENT Surname_leader_team (#PCDATA)>
        <!ELEMENT Country_base_location (#PCDATA)>
        <!ELEMENT Personal_number_first_pilot (#PCDATA)>
        <!ELEMENT Personal_number_second_pilot (#PCDATA)>
        <!ELEMENT Grand_prix (Number|Year|Host_country|Name_track|Number_circles|Track_km)*>
        <!ELEMENT Number (#PCDATA)>
        <!ELEMENT Year (#PCDATA)>
        <!ELEMENT Host_country (#PCDATA)>
        <!ELEMENT Name_track (#PCDATA)>
        <!ELEMENT Number_circles (#PCDATA)>
        <!ELEMENT Track_km (#PCDATA)>
        <!ELEMENT Results_qualification (Id_result|Id_grand_prix|Date_qual|Posittion|Number_pilot|Time)*>
        <!ELEMENT Id_result (#PCDATA)>
        <!ELEMENT Id_grand_prix (#PCDATA)>
        <!ELEMENT Date_qual (#PCDATA)>
        <!ELEMENT Posittion (#PCDATA)>
        <!ELEMENT Number_pilot (#PCDATA)>
        <!ELEMENT Time (#PCDATA)>
        <!ELEMENT Results_race (Id_result|Id_grand_prix|Date_race|Posittion|Number_pilot|Time|Elimination)*>
        <!ELEMENT Date_race (#PCDATA)>
        <!ELEMENT Elimination (#PCDATA)>]><Formula_1 xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ./Formula1.xsd"><Pilots><Personal_pilot_number>2</Personal_pilot_number><Name>Стоффель</Name><Surname>Вандорн</Surname><Date_of_birth>1991-03-26</Date_of_birth></Pilots><Pilots><Personal_pilot_number>3</Personal_pilot_number><Name>Даниэль</Name><Surname>Риккардо</Surname><Date_of_birth>1989-07-01</Date_of_birth></Pilots><Pilots><Personal_pilot_number>5</Personal_pilot_number><Name>Себастьян</Name><Surname>Фетель</Surname><Date_of_birth>1987-07-03</Date_of_birth></Pilots><Bolids><Name_bolid>Ferrari SF71H</Name_bolid><Name_engine>Ferrari 062 EVO 1.6 V6t</Name_engine><Name_chassis>Ferrari SF71H</Name_chassis><Year_bolid>2018</Year_bolid></Bolids><Bolids><Name_bolid>Force India VJM11</Name_bolid><Name_engine>Force India VJM11</Name_engine><Name_chassis>Mercedes M09 EQ Power+ 1.6 V6T</Name_chassis><Year_bolid>2018</Year_bolid></Bolids><Teams><Name_team>Alfa Romeo Sauber F1 Team 2018</Name_team><Year_team>2018</Year_team><Name_leader_team>Фредерик</Name_leader_team><Surname_leader_team>Вассеур</Surname_leader_team><Country_base_location>Швейцария</Country_base_location><Name_bolid>Sauber C37</Name_bolid><Personal_number_first_pilot>9</Personal_number_first_pilot><Personal_number_second_pilot>16</Personal_number_second_pilot></Teams><Grand_prix><Number>1</Number><Year>2018</Year><Host_country>Австралия</Host_country><Name_track>Australian Grand Prix</Name_track><Number_circles>57</Number_circles><Track_km>5.7</Track_km></Grand_prix><Results_qualification><Id_result>1</Id_result><Id_grand_prix>1</Id_grand_prix><Date_qual>2018-03-24</Date_qual><Posittion>1</Posittion><Number_pilot>44</Number_pilot><Time>00:01:21.164</Time></Results_qualification><Results_race><Id_result>1</Id_result><Id_grand_prix>1</Id_grand_prix><Date_race>2018-03-25</Date_race><Posittion>1</Posittion><Number_pilot>5</Number_pilot><Time>01:29:33.283</Time><Elimination>false</Elimination></Results_race></Formula_1>
